### ISSUE TITLE
Add navigation and breadcrumb trail

### ISSUE THREAD

**Issue by MikeThacker1** [tpximpact/mhclg-oruk#41]

**Comment by gjhltn** [comment]
Is done

**Comment by MikeThacker1** [comment]
I can't see this live from [the main page](https://openreferraluk.netlify.app/) (or any other page).
@gjhltn will you show me this when we chat please?

**Comment by gjhltn** [comment]
This is on the work in progress site, but is specifically NOT on the demo site because we aren't demoing it. It's been there for several weeks actually!On 15 Nov 2024, at 13:15, MikeThacker1 ***@***.***> wrote:﻿
I can't see this live from the main page (or any other page).
@gjhltn will you show me this when we chat please?
