### ISSUE TITLE
Enable option to select schema version when submitting for testing

### ISSUE THREAD

**Issue by DaveIlesTPX** [tpximpact/mhclg-oruk#49]
Someone in the process of developing their API might want to check its compliance against the validator. 
If they have not got the `GET /` endpoint working and returning the correct `version` it may not be possible for them to test the endpoints that have been developed.

**Comment by gjhltn** [comment]
If we have defaulted to v1 - the json response will need a way to state this - I suppose we could put up an explanatory message along the lines of 'because the root endpoint doesn't specify a version, we're falling back to v1. To validate against a newer standard, implement a version field with the appropriate value'.... or something...?

**Comment by MikeThacker1** [comment]
Yes. Something like that text would be good. Agreed we are reading the version from the root URL (or its absence), not asking the user to specify.

**Comment by gjhltn** [comment]
Going to mark this as a wont fix.
